joypad_input = 'FF00';
serial_transfer_data = 'FF01';
serial_transfer_control = 'FF02';
divider_register = 'FF04';
timer_counter = 'ff05';
timer_modulo = 'ff06';
timer_control = 'ff07';
interrupt_flags = 'ff0f';
channel1_sweep = 'ff10';
channel1_duty_timer = 'ff11';
channel1_volume_envelope = 'ff12';
channel1_period_L = 'ff13';
channel1_period_H_control = 'ff14';
channel2_duty_timer = 'ff16';
channel2_volume_envelope = 'ff17';
channel2_period_L = 'ff18';
channel2_period_H_control = 'ff19';
channel3_DAC_enable = 'ff1a';
channel3_length_timer = 'ff1b';
channel3_output_level = 'ff1c';
channel3_period_L = 'ff1d';
channel3_period_H_control = 'ff1e';
channel4_length_timer = 'ff20';
channel4_volume_envelope = 'ff21';
channel4_frequency_randomness = 'ff22';
channel4_control = 'ff23';
master_volume_VIN_panning = 'ff24';
sound_panning = 'ff25';
audio_master_control = 'ff26';


i=1;
for r = hex2dec('ff30'):hex2dec('ff3f');
  channel3_wave_ram{i} = dec2hex(r,4);
  i = i + 1;
end

LCD_control = 'ff40';
LCD_status = 'ff41';
SCY = 'ff42';
SCX = 'ff43';
LCD_Y = 'ff44';
LY_compare = 'ff45';
BG_palette = 'ff47';
OBP0 = 'ff48';
OBP1 = 'ff49';
window_Y = 'ff4a';
window_X = 'ff4b';
interrupt_enable = 'ffff';
