disp(['turn on screen subroutine: ', dec2hex(PC)]);
turn_on_screen = dec2hex(PC,4);
PUSH_HL();
LD_HL(LCD_control);
SET_7_pHLp();
SET_4_pHLp();
SET_0_pHLp();
LD_HL(BG_palette);
LD_pHLp('E4');
POP_HL();
RET();